### ISSUE TITLE
look for alternativ spi library or improve current one

### ISSUE THREAD

**Issue by schneider42** [muccc/flipdots#7]
the current one is slow and produces strange pulses on the /CS line.

Have a look a https://github.com/mstaflex/SPI-Py or quick to wire

**Comment by dergigo** [comment]
@schneider42 are you still working on it?

**Comment by schneider42** [comment]
We will replace the whole thing with direct GPIO access and remove the SPI port expander.

**Comment by morawekj** [comment]
Neues PCB ?, ein Level Shifter wäre als Busentkopplung Sinnvoll
